[profile.default]
src = "src"
out = "out"
libs = ['node_modules', 'lib']

solc = '0.8.25'

remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@chainlink/contracts-ccip/=node_modules/@chainlink/contracts-ccip/',
    '@chainlink/local/=lib/chainlink-local/'
]

