[profile.default]
src = "src"
out = "out"
libs = ['node_modules', 'lib']

solc = '0.8.25'

remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@chainlink/contracts-ccip/=node_modules/@chainlink/contracts-ccip/',
    '@chainlink/local/=lib/chainlink-local/'
]

[etherscan]
sepolia = { key = "JGWS1C3GSNW3GQYVU5AHMB5Y2I9KUI6YHW" }
base ={key = "6JHTJ2RIUFUFUIE5SQS1AXM5BBMVVXHMYI"}

